name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.3.1
        with: 
          filename: modulo5/4.aws-gitactions.js

      - name: step 3 - check for index.html and move to report
        run: |
          echo "Listando arquivos no diret처rio atual:"
          ls -al
          mkdir -p report
          if [ -f index.html ]; then
            echo "index.html encontrado. Movendo para o diret처rio report."
            mv index.html report/
          else
            echo "index.html n찾o encontrado."
          fi

      - name: step 4 - verify report directory
        run: |
          echo "Listando arquivos no diret처rio report:"
          ls -al report

      - name: step 5 - upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: relatorio de testes de performance
          path: report
